version: '3.8'

services:
  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./conf:/conf/

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=casdoor
      - POSTGRES_PASSWORD=casdoor_password
      - POSTGRES_DB=casdoor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
